spring:
  application:
    name: sample-erudio-mcp-client
  ai:
    openai:
      api-key: ${OPEN_AI_API_KEY}
#  spring.ai.mcp.client.sse.transport-mode=WEBFLUX  # or HTTP_CLIENT
#      chat:
#        options:
#          model: gpt-4-0125-preview
    mcp:
      client:
        toolcallback:
          enabled: true
        sse:
          connections:
            person-erudio-mcp-service:
              url: http://localhost:8060
            account-erudio-mcp-service:
              url: http://localhost:8040
          transport-mode: WEBFLUX

logging:
  level:
    org.springframework.ai: DEBUG